# Use the official OpenJDK base image
FROM openjdk:11-jre-slim

# Set the working directory
WORKDIR /app

# Copy the JAR file into the container at /app
COPY target/trip.jar /app/tripservice.jar

# Specify the command to run on container start
CMD ["java", "-jar", "tripservice.jar"]

EXPOSE 8002
